Fix compile error in 0.9.0
libpki 0.9.0 will not compile on CentOS 8. It fails with an error on line 86 of src/pki_config.c:

 error: 'strncpy' specified bound depends on the length of the source argument.

Since the destination buffer, ret, is allocated a buffer of size strlen(my_search)+1, there doesn't seem to be a reason to use strncpy rather than strcpy.